Initial scaffolding for the new linter, without any rules implemented yet
Polymer/polymer-linter pull request #10
Opened 2016-12-21 19:53 UTC by rictic

Extracted by rictic from usergenic's https://github.com/Polymer/polymer-linter/pull/1 PR

2016-12-21 20:05 UTC, usergenic requested changes

2016-12-21 20:05 UTC, usergenic commented on src/linter.ts
> +        if (error instanceof WarningCarryingException) {
Can we catch per-rule?  That way all rules will try to run if one fails.

2016-12-21 20:06 UTC, usergenic commented on src/linter.ts
> +        if (error instanceof WarningCarryingException) {
If not here, lets file issue and move that code in separate PR?

2016-12-21 21:02 UTC, rictic commented on src/linter.ts
> +        if (error instanceof WarningCarryingException) {
+1, reworked how we do error handling here, PTAL

2016-12-21 22:33 UTC, usergenic commented on src/linter.ts
> +        warnings = warnings.concat(await rule.check(document));
Can we add a TODO (or implement?) here to catch exceptions for the `rule.check()` call?  I'd be nice if we had a standard warning to push like we do in the `_analyzeAll` call.

2016-12-21 23:49 UTC, rictic commented on src/linter.ts
> +        warnings = warnings.concat(await rule.check(document));
+1, done

2016-12-21 23:54 UTC, usergenic approved these changes
This is all sorts of LGTM

2016-12-22 00:30 UTC, rictic commented
Thanks for the review!

2016-12-22 00:30 UTC, merged