Add unbalanced polymer databinding delimitors rule.
Polymer/polymer-linter pull request #23
Opened 2017-02-15 20:21 UTC by rictic

- [x] CHANGELOG.md has been updated

Steals from @usergenic's PR #1

2017-02-15 23:28 UTC, rictic commented
Fixes #30

2017-02-23 21:46 UTC, usergenic requested changes

2017-02-23 21:46 UTC, usergenic commented on src/polymer/matchers.ts
> +export function getNestedDataBindingTemplates(node: parse5.ASTNode) {
I feel like this needs commenting.  Also, I feel like matchers.ts should be all predicate functions, but maybe that wouldn't make sense for this one, so not a deal-breaker.

2017-02-24 15:26 UTC, rictic commented on src/polymer/matchers.ts
> +export function getNestedDataBindingTemplates(node: parse5.ASTNode) {
It turns out that this can be written more correctly as a predicate (as top level dom-if and dom-repeat is allowed, it turns out.

2017-02-24 17:24 UTC, usergenic commented on src/polymer/matchers.ts
> +export function getNestedDataBindingTemplates(node: parse5.ASTNode) {
So clean!  Awesome.

2017-02-24 17:25 UTC, usergenic approved these changes
LGTM

2017-02-25 01:12 UTC, merged