Polymer 2.0 elements must call super.callback()
Polymer/polymer-linter pull request #53
Opened 2017-03-13 17:54 UTC by rictic

Fixes #52 

 - [x] CHANGELOG.md has been updated

2017-03-13 18:42 UTC, justinfagnani commented
@rictic I think this might need a little more specification.

Elements with a known super class probably want to call `super.X()` if `X` is know to be defined at compile time, whether or not the elements are vanilla.

Mixins however should probably always do a guarded call, like

```
if (super. X) super.X();
```

And of course there are cases where you want to not can super on purpose.

2017-03-13 18:53 UTC, rictic commented
I agree with all of those objections, but as I understand them they only apply to a generalization of this lint pass.

Every Polymer 2.0 element should call super in `connectedCallback`, `disconnectedCallback`, `attributesChangedCallback`, and the constructor or they'll get undefined behavior that may change from minor version to minor version of Polymer. I think that's always true.

The generalized form is much harder to define and write. I think it'd involve something like an `@mustCallSuperInOverrides` (🚲🏡)  jsdoc annotation on a method.

I think this specific form is valuable, as people have been running into this error in the wild, and the failure mode is a mysterious and hard to track down. The element just doesn't stamp out its template.

2017-03-13 19:18 UTC, justinfagnani commented
I think we need to be careful with the phrase "every Polymer element", because in 2.0 that doesn't mean that you extend from `Polymer.Element` or even have `ElementMixin` applied. Mainly what being a Polymer element means right now is that we read `is` and `properties`. So a Polymer element might not have a callback defined. And a vanilla element may extend a base class or apply a mixin with a callback defined.

We can actually check whether we see a callback and lint based on that with no fork on polymer vs vanilla.

2017-03-13 19:25 UTC, rictic commented
Oh, you mean like looking up the inheritance graph to see if anything up there defines any of the callbacks and assuming that they're required if defined? Yeah that makes sense to me. I'll take a shot.

2017-03-13 20:55 UTC, rictic commented
@justinfagnani Done, PTAL

2017-03-13 21:11 UTC, justinfagnani requested changes

2017-03-13 21:11 UTC, justinfagnani commented on src/polymer/call-super-in-callbacks.ts
> +    for (const element of document.getByKind('polymer-element')) {
Why is this polymer-element, and not element? And should this also contain element-mixin?

2017-03-13 21:11 UTC, justinfagnani commented on src/polymer/call-super-in-callbacks.ts
> +      // TODO(rictic): methods should have astNodes, that would make this
Add an issue on the analyzer

2017-03-13 21:11 UTC, justinfagnani commented on src/polymer/call-super-in-callbacks.ts
> +                Elements that extend Polymer.Element must call
Remove Polymer.Element add class or mixin that declares method

2017-03-13 21:11 UTC, justinfagnani commented on src/polymer/call-super-in-callbacks.ts
> +function mustCallSuper(
You might want to return the feature that defined the method

2017-03-13 21:11 UTC, justinfagnani commented on src/polymer/call-super-in-callbacks.ts
> +  const superCallTargets = statements.map((s) => {
It looks like this only finds top level calls. As a test for a mixin that conditionally calls the super method.

2017-03-14 00:14 UTC, rictic commented on src/polymer/call-super-in-callbacks.ts
> +    for (const element of document.getByKind('polymer-element')) {
Now querying for elements and element mixins.

Now blocked on a tiny PR in the analyzer: https://github.com/Polymer/polymer-analyzer/pull/561

Tests will fail until that's released.

2017-03-14 00:14 UTC, rictic commented on src/polymer/call-super-in-callbacks.ts
> +      // TODO(rictic): methods should have astNodes, that would make this
Done

2017-03-14 00:14 UTC, rictic commented on src/polymer/call-super-in-callbacks.ts
> +                Elements that extend Polymer.Element must call
Rewrote, PTAL

2017-03-14 00:14 UTC, rictic commented on src/polymer/call-super-in-callbacks.ts
> +function mustCallSuper(
+1.

Returned a string representation.

2017-03-14 00:14 UTC, rictic commented on src/polymer/call-super-in-callbacks.ts
> +  const superCallTargets = statements.map((s) => {
Yeah, I was overly narrow. Changed to being overly broad. Added test.

2017-03-14 06:10 UTC, justinfagnani commented on src/polymer/call-super-in-callbacks.ts
> +    return `the mixin's given superclass`;
I don't quite read this string. A mixin doesn't have a superclass.

2017-03-14 06:10 UTC, justinfagnani commented on src/polymer/call-super-in-callbacks.ts
> +    // TODO(rictic): if mixins had their own mixins pre-mixed in we wouldn't
file issue?

2017-03-14 06:10 UTC, justinfagnani commented on src/polymer/call-super-in-callbacks.ts
> +    // TODO(rictic): once we have a representation of a Class this should be
file issue?

2017-03-14 06:10 UTC, justinfagnani commented on src/polymer/call-super-in-callbacks.ts
> +function definesMethod(
doc that because we copy down properties this finds methods up the inheritance chain

2017-03-14 06:35 UTC, rictic commented on src/polymer/call-super-in-callbacks.ts
> +    return `the mixin's given superclass`;
I'm trying to come up with something better than `mixedin` :)

How about `a class this mixin extends`?

2017-03-14 06:37 UTC, justinfagnani commented on src/polymer/call-super-in-callbacks.ts
> +    return `the mixin's given superclass`;
But there is no such class. What entity are you referring to here?

2017-03-14 06:38 UTC, rictic commented on src/polymer/call-super-in-callbacks.ts
> +    return `the mixin's given superclass`;
e.g. `superClass` in this example:

```javascript
function myMixin(superClass) {
  return class extends superClass { /* ... */ }
}
```

2017-03-14 06:40 UTC, justinfagnani commented on src/polymer/call-super-in-callbacks.ts
> +    return `the mixin's given superclass`;
That's just a parameter, so it can't really be the source of a method no?

2017-03-14 06:44 UTC, rictic commented on src/polymer/call-super-in-callbacks.ts
> +    return `the mixin's given superclass`;
So given the assumptions:

  1. if a class's superclass defines a custom element callback, and you override it, you must call super.thatCallback()
  2. a mixin may be mixed into any class (or any element class, same diff)

then it follows that any mixin that implements a custom element callback must conditionally call that callback.

2017-03-14 06:55 UTC, rictic reviewed
Comments addressed except for the recent long mixin thread which got messed up because github.

2017-03-14 06:55 UTC, rictic commented on src/polymer/call-super-in-callbacks.ts
> +    // TODO(rictic): once we have a representation of a Class this should be
Done

2017-03-14 06:56 UTC, rictic commented
Sidenote but we should really try reviewable. I know it's got an overcomplicated interface, but it seems like it is doing a better job of representing what's going on in a code review of a PR.

2017-03-15 00:25 UTC, rictic commented
Ok, new version of analyzer is used now, tests pass, PTAL.

2017-03-15 00:49 UTC, justinfagnani commented on src/polymer/call-super-in-callbacks.ts
> +    return `the mixin's given superclass`;
Ok, if the resultant message reads something like we talked about it's fine.

2017-03-15 00:49 UTC, justinfagnani approved these changes

2017-03-15 02:54 UTC, merged